system:
  display:
    DISPLAY_W: 800
    DISPLAY_H: 480
    TOP_BAR_SIZE: 64
    TARGET_FPS: 60
  switcher:
    BUTTONS_X: 4
    BUTTON_H: 64
    BUTTON_MARGIN: 2

modules:
  panadapter:
    type: rtl_fft
    display_name: panadapter
    config:
      IF_FREQ: 124488500 # 124487000 + 1500
      SAMPLE_RATE: 1200000
      INVERTED: true
      GRAPH_HEIGHT: 64
      BUTTON_HEIGHT: 48
      RF_MIN: 0
      RF_MAX: 500
      SAMPLE_PROVIDER: random
      CURRENT_FREQ: 7055000
  
  gpsd:
    type: gpsd
    display_name: GPS Status
    config:
      server: localhost:2947
  
  modem:
    type: lte_status
    display_name: 4G Status
    config:
      backend: test
      line_height: 32

waterfall_server:
  listen_port: 45362
  device_serial: '00000007'
  if_freq: 124488500 # 124487000 + 1500
  sample_rate: 1200000

theme:
  defaults:
    colours:
      normal_bg: "#4c5052"
      hovered_bg: "#63686b"
      disabled_bg: "#25292e"
      selected_bg: "#365880"
      active_bg: "#365880"
      dark_bg: "#21282d"
      disabled_dark_bg: "#181818"
      normal_text: "#bbbbbb"
      hovered_text: "#bbbbbb"
      disabled_text: "#808080"
      selected_text: "#bbbbbb"
      active_text: "#bbbbbb"
      normal_border: "#5c6062"
      hovered_border: "#73787b"
      disabled_border: "#35393e"
      selected_border: "#466890"
      active_border: "#466890"
      link_text: "#6897bb"
      link_hover: "#84bfed"
      link_selected: "#84bfed"
      text_shadow: "#777777"
      filled_bar: "#f4251b"
      unfilled_bar: "#CCCCCC"
  '#param_label':
    colours:
      normal_text: "#FF00FF"
      dark_bg: "#151D22"
    font:
      name: "fira_code"
      size: 14
      bold: 1